# Generated by Django 5.2.1 on 2025-05-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField(blank=True)),
                ('pet_type', models.CharField(choices=[('ct', 'Cat'), ('dg', 'Dog'), ('hmtr', 'Hamster'), ('prrt', 'Parrot'), ('fsh', 'Fish'), ('other', 'Other')], max_length=20)),
            ],
        ),
    ]
